spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
    add-properties: false

logging:
  level:
    org:
      springframework: DEBUG
      springframework.web: DEBUG